---

provision:
  hosts:
    localhost:
  vars:
    ce_provision:
      own_repository: https://github.com/codeenigma/ce-provision.git
      config_repository: https://github.com/codeenigma/ce-provision-config-example.git
