---

provision:
  hosts:
    localhost:
  vars:
    ansible_provision:
      own_repository: https://github.com/codeenigma/ansible-provision.git
      config_repository: https://github.com/codeenigma/ansible-provision-config-example.git
